LibarySystem/LibarySystem/Models/ErrorViewModel.cs
using System;

namespace LibarySystem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibarySystem/LibarySystem/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibarySystem.data;
using System.IO;
using Microsoft.Extensions.Configuration;


namespace LibarySystem.Controllers
{
    public class AuthorsController : Controller
    {
        IAuthor authorservice;
        IConfiguration configuration;
        INutionalityService nutionalityService;
        public AuthorsController(IAuthor _authorService,IConfiguration _configuration,INutionalityService _nutionalityService)
        {
            authorservice = _authorService;
            configuration = _configuration;
            nutionalityService = _nutionalityService;
        }
        public IActionResult Index(VMAuthor vm)
        {
            List<Nutionality> _linutionality = nutionalityService.loadAllNution();
            List<Author> _liauthors = authorservice.data();
            vm.linutionality = _linutionality;
            vm.liAuthor = _liauthors;
            return View("AuthorSec",vm);
        }

        public IActionResult SaveData(VMAuthor vm)
        {
            string filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\" + configuration["filePath"], vm.ProfileImage.FileName);
            vm.ProfileImage.CopyTo(new FileStream(filePath, FileMode.Create));
            vm.author.path = "http://localhost/LibarySystem//" + configuration["filePath"] + "/" + vm.ProfileImage.FileName;
            authorservice.Insert(vm.author);
            List<Nutionality> _linutionality = nutionalityService.loadAllNution();
            List<Author> liauthors = authorservice.data();
            vm.liAuthor = liauthors;
            vm.linutionality = _linutionality;
            return View("AuthorSec",vm);
        }

        public IActionResult DeleteData(int id,VMAuthor vm)
        {
            authorservice.Delete(id);
            List<Nutionality> _linutionality = nutionalityService.loadAllNution();
            List<Author> _liauthors = authorservice.data();
            vm.linutionality = _linutionality;
            vm.liAuthor = _liauthors;
            return View("AuthorSec", vm);
        }
    }
}

LibarySystem/LibarySystem/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibarySystem.data;
using System.IO;
using Microsoft.Extensions.Configuration;

namespace LibarySystem.Controllers
{
    public class BookController : Controller
    {
        ICategoryService categoryService;
        IAuthor author;
        IBookService BookService;
        VMBook vm;
        IConfiguration configuration;

        public BookController(ICategoryService _categoryService,IAuthor _author, IBookService _BookService, IConfiguration _configuration)
        {
            categoryService = _categoryService;
            author = _author;
            BookService = _BookService;
            vm = new VMBook();
            configuration = _configuration;
        }
        public IActionResult Index()
         {
            vm.liBook= BookService.returnData();
            vm.liauthor = author.data();
            vm.licategory = categoryService.returndata();

            return View("BookSec",vm);
        }

        public IActionResult SaveData(VMBook vm)
        {
            string filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\" + configuration["filePath"], vm.ProfileImage.FileName);
            vm.ProfileImage.CopyTo(new FileStream(filePath, FileMode.Create));
            vm.book.path = "http://localhost/LibarySystem//" + configuration["filePath"] + "/" + vm.ProfileImage.FileName;
            BookService.Insert(vm.book);
            List<Category> x = categoryService.returndata();
            List<Author> a = author.data();
            List<Book> b = BookService.returnData();
            vm.liBook = b;
            vm.licategory = x;
            vm.liauthor = a;
            return View("BookSec",vm);
        }

        public IActionResult DeleteData(VMBook vm,int id)
        {
            BookService.Delete(id);
            vm.liBook = BookService.returnData();
            vm.liauthor = author.data();
            vm.licategory = categoryService.returndata();
            return View("BookSec", vm);
        }


    }
}

LibarySystem/LibarySystem/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibarySystem.data;

namespace LibarySystem.Controllers
{
    public class CategoryController : Controller
    {
        
        ICategoryService categoryService;
        public CategoryController(ICategoryService _categoryService)
        {

            categoryService = _categoryService;
        }
        public IActionResult Index(VMCategory vm)
        {
            List<Category> x = categoryService.returndata();
            vm.licategory = x;
            return View("CategorySec", vm);
        }

        public IActionResult SaveData(VMCategory vm)
        {
            categoryService.Insert(vm);
            List<Category> categories = categoryService.returndata();
            vm.licategory = categories;
            return View("CategorySec",vm);
        }

        public IActionResult DeleteData(int id,VMCategory vm)
        {
            categoryService.Delete(id);
            List<Category> x = categoryService.returndata();
            vm.licategory = x;
            return View("CategorySec",vm);
        }
    }
}

LibarySystem/LibarySystem/Controllers/HomeController.cs
using LibarySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LibarySystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibarySystem/LibarySystem/Views/Authors/AuthorSec.cshtml
@model VMAuthor
@{
    ViewData["Title"] = "AuthorSec";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@section Body
{

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1> Authors Section </h1>
            </div>
        </div>

    </div>

}
@section Body2 {
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <input type="submit" value="New Authors" data-target="#testmodal" data-toggle="modal" class="btn btn-primary" />
            </div>
            <div class="row" style="margin-top:50px">
                <div class="col-lg-12">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th>Name</th>
                                <th> Image</th>
                                <th> Action </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Author item in Model.liAuthor)
                            {

                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.FName</td>
                                    <td>
                                        <img src="@item.path" style="width:100px" />
                                    </td>
                                    <td>
                                        <a class="text-primary"> Edit  </a>|
                                        <a class="text-primary" asp-action="DeleteData" asp-route-id=@item.ID> Delete </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form method="post" enctype="multipart/form-data">
        <div class="modal fade" id="testmodal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"> Authors </h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <span> First Name</span>
                            <input type="text" class="form-control" placeholder="First Name" asp-for="author.FName" />
                        </div>
                        <div style="margin-top:15px">
                            <span> Last Name</span>
                            <input type="text" class="form-control" placeholder="Last Name" asp-for="author.LName" />
                        </div>
                        <div style="margin-top:15px">
                            <span> Nutionality </span>
                            <select class="form-control" asp-items='new SelectList(Model.linutionality,"ID","Name")' asp-for="author.Nutionality_id"></select>
                        </div>
                        <div style="margin-top:15px">
                            <input type="file" id="fileUp" asp-for="ProfileImage" style="display:none;" />
                            <label class="btn btn-primary" for="fileUp">Upload Image</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" value="Save" class="btn btn-primary" asp-action="SaveData" />
                        <input type="submit" value="Close" class="btn btn-primary" />
                    </div>
                </div>

            </div>
        </div>
    </form>

}

LibarySystem/LibarySystem/Views/Book/BookSec.cshtml
@model VMBook
@{
    ViewData["Title"] = "BookSec";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@section Body
{

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1> Book Section </h1>
            </div>
        </div>

    </div>

}
@section Body2 {
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <input type="submit" value="New Book" data-target="#testmodal" data-toggle="modal" class="btn btn-primary" />
                </div>
                <div class="row" style="margin-top:50px">
                    <div class="col-lg-12">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                                <tr>
                                    <th> # </th>
                                    <th>Book title</th>
                                    <th> Cover</th>
                                    <th> Year</th>
                                    <th> price</th>
                                    <th> Category</th>
                                    <th> Authors</th>
                                    <th> Stock</th>
                                    <th> Action </th>
                                </tr>
                            </thead>
                           
                            <tbody>
                                @foreach (Book item in Model.liBook)
                                {
                                    <tr>
                                        <td>@item.ID</td>
                                        <td>@item.title</td>
                                        <td>
                                            <img src="@item.path" style="width:100px" />
                                        </td>
                                        <td>@item.year</td>
                                        <td>@item.price</td>
                                        <td>@item.category.Name</td>
                                        <td>@item.author.FName</td>
                                        <td>@item.stock</td>
                                        <td>
                                            <a class="text-primary">Edit</a> |
                                            <a class="text-primary" asp-action="DeleteData" asp-route-id=@item.ID >Delete</a>
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            
                        </table>
                    </div>
                </div>
            </div>
        </div>
    
    <form method="post" enctype="multipart/form-data">
        <div class="modal" id="testmodal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"> Book details </h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <span> Book title</span>
                            <input type="text" class="form-control" placeholder="Book title " asp-for="book.title" />
                        </div>
                        <div style="margin-top:15px">
                            <span> Year </span>
                            <input type="text" class="form-control" placeholder="Year" asp-for="book.year" />
                        </div>
                        <div style="margin-top:15px">
                            <span> Price </span>
                            <input type="text" class="form-control" placeholder="Price" asp-for="book.price" />
                        </div>
                        <div style="margin-top:15px">
                            <span> Category </span>
                            <select class="form-control" asp-items='new SelectList(Model.licategory,"ID","Name")' asp-for="book.category_id"></select>
                        </div>
                        <div style="margin-top:15px">
                            <span> Autors </span>
                            <select class="form-control" asp-items='new SelectList(Model.liauthor,"ID","FName")' asp-for="book.author_id"></select>
                        </div>
                        <div style="margin-top:15px">
                            <input type="file" id="fileUp" asp-for="ProfileImage" style="display:none;" />
                            <label class="btn btn-primary" for="fileUp" >Cover photo</label>
                        </div>
                        <div style="margin-top:15px">
                            <span> Stock </span>
                            <input type="text" class="form-control" placeholder="Stock" asp-for="book.stock" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" value="Save" class="btn btn-primary" asp-action="SaveData" />
                        <input type="submit" value="Close" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </form>

}

LibarySystem/LibarySystem/Views/Category/CategorySec.cshtml
@model VMCategory

@{
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@section Body
{

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1> Category Section </h1>
            </div>
        </div>

    </div>
}
@section Body2{

    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <input type="submit" value="New Category" data-target="#testmodal" data-toggle="modal" class="btn btn-primary" />
            </div>

            <div class="row" style="margin-top:50px">
                <div class="col-lg-12">

                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th>Category Code</th>
                                <th>Category Name</th>
                                <th> Action </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Category item in Model.licategory)
                            {
                             
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.Code</td>
                                    <td>@item.Name</td>
                                    <td>
                                        <a class="text-primary"> Edit  </a>|
                                        <a class="text-primary" asp-action="DeleteData" asp-route-id=@item.ID> Delete </a>
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

    <form method="post">
        <div class="modal fade" id="testmodal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"> Category </h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <span> Category Code</span>
                            <input type="text" class="form-control" placeholder="Category Code" asp-for="category.Code" />
                        </div>
                        <div>
                            <span> Category Name</span>
                            <input type="text" class="form-control" placeholder="Category Name" asp-for="category.Name" />
                        </div>
                    </div>

                    <div class="modal-footer">
                        <input type="submit" value="Save" class="btn btn-primary" asp-action="SaveData" />
                        <input type="button" value="Close" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </form>

}

LibarySystem/LibarySystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LibarySystem/LibarySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibarySystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibarySystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LibarySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LibarySystem/LibarySystem/Views/Shared/_LayoutPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LayoutPage</title>
    <link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
    <script src="~/js/Book.js"></script>

    @RenderSection("head", false)
</head>
<body>
    <div id="throbber" style="display:none; min-height:120px;"></div>
    <div id="noty-holder"></div>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="https://bryanrojasq.wordpress.com">
                    <img src="http://placehold.it/200x50&text=LOGO" alt="LOGO">
                </a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li>
                    <a href="#" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Stats">
                        <i class="fa fa-bar-chart-o"></i>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin User <b class="fa fa-angle-down"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="fa fa-fw fa-user"></i> Edit Profile</a></li>
                        <li><a href="#"><i class="fa fa-fw fa-cog"></i> Change Password</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-fw fa-power-off"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">

                    <li>
                        <a asp-action="Index" asp-controller="Category"><i></i> Category Section </a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Authors"><i></i> Authors Section</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Book"><i></i> Books Section </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row" id="main">
                    <div class="col-sm-12 col-md-12 well" id="content">
                        @RenderSection("Body")
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
        @RenderSection("Body2")
    </div><!-- /#wrapper -->

</body>
</html>